@startuml logout
actor User
boundary "System" as system
control "Sessions" as sessions
control "Authentication" as auth
User -> system: Logout
activate system
system -> auth: is_logged_in(username, udb)
activate auth
auth --> system: True
system -> auth: logout_user(username)
auth --> system: True
deactivate auth
system -> sessions: remove_current_session(username, db)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to login
deactivate system
@enduml