@startuml register
actor User
boundary "System" as system
control "sessions" as sessions
database "Database" as db 
User -> system: Register
activate system
system -> db: add_new_user(username, password, email)
activate db
db --> system: True
deactivate db
system -> sessions: add_new_session(username, db)
activate sessions
sessions --> system: None
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml 

