@startuml viewProfile
actor Customer
boundary "System" as system
control "authentication" as auth 
Database "User Database" as udb 
Customer -> system: View Profile
activate system
system -> auth: is_logged_in(username, udb)
activate auth
auth --> system: True
deactivate auth
system -> udb: view_profile(username)
activate udb
udb --> system: Profile
deactivate udb
system -> system: Display profile
@enduml 